name: Deploy Elasticsearch to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Helm lint
        run: helm lint .

      - name: Deploy Elasticsearch Helm Chart
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl config use-context minikube
          helm upgrade --install elasticsearch elastic/elasticsearch -n elasticsearch -f values.yaml --create-namespace
