name: Deploy Elasticsearch to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Add KUBECONFIG secret if you use it for Minikube remote access
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy Elasticsearch Helm Chart
        run: |
          kubectl config use-context minikube
          helm upgrade --install elasticsearch elastic/elasticsearch -n elasticsearch -f values.yaml --create-namespace
